package com.komehyo.dao.mapper.config;

import com.komehyo.dao.entity.International;

public interface InternationalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_c_international
     *
     * @mbg.generated
     */
    int insert(International record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_c_international
     *
     * @mbg.generated
     */
    int insertSelective(International record);


    International selectById(String id);
}