server:
  port: 8085
  servlet:
    context-path: /komehyo
  tomcat:
    accept-count: 100
    max-threads: 100
    max-connections: 200
#  ssl:
#    enabled: true
#    key-store: C:\apache-tomcat-7.0.105\cert\komehyo-china.com.pfx
#    key-store-password: V5YfUF07
#    key-store-type: PKCS12


spring:
  application:
    name: komehyo
  banner:
    location: Budda.txt
  datasource:
    app:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.26:3306/g1_app_d9503?autoReconnect=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: dita2020
      password: U3o6dZrxNPCONHxD7m6USQ==
      driver-class-name: com.mysql.cj.jdbc.Driver
    config:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.26:3306/g1_app_d9503?autoReconnect=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: dita2020
      password: U3o6dZrxNPCONHxD7m6USQ==
      driver-class-name: com.mysql.cj.jdbc.Driver


itext:
  pdf:
    widthA: 4.25
    widthB: 4.25
    widthC: 1.13
    widthD: 3.25
    widthE: 4.25
  image:
    width: 3.5
    height: 2.5

file:
  pdf:
    path: D:\outTest\pdf\
  zip:
    path: D:\outTest\zip\
  barcode:
    path: D:\outTest\barcode\
  template:
    path: D:\outTest\template\good_import.xlsx

logging:
  level:
    root: info
  path: ./logs

#mybatis:
#  mapper-locations: classpath*:**/*Mapper.xml








