package com.komehyo.dao.entity;

import java.util.Date;

public class BeltMaterial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column belt_material.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column belt_material.belt_material
     *
     * @mbg.generated
     */
    private String beltMaterial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column belt_material.cre_user
     *
     * @mbg.generated
     */
    private String creUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column belt_material.cre_date
     *
     * @mbg.generated
     */
    private Date creDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column belt_material.upd_user
     *
     * @mbg.generated
     */
    private String updUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column belt_material.upd_date
     *
     * @mbg.generated
     */
    private Date updDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column belt_material.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column belt_material.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column belt_material.id
     *
     * @return the value of belt_material.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column belt_material.id
     *
     * @param id the value for belt_material.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column belt_material.belt_material
     *
     * @return the value of belt_material.belt_material
     *
     * @mbg.generated
     */
    public String getBeltMaterial() {
        return beltMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column belt_material.belt_material
     *
     * @param beltMaterial the value for belt_material.belt_material
     *
     * @mbg.generated
     */
    public void setBeltMaterial(String beltMaterial) {
        this.beltMaterial = beltMaterial == null ? null : beltMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column belt_material.cre_user
     *
     * @return the value of belt_material.cre_user
     *
     * @mbg.generated
     */
    public String getCreUser() {
        return creUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column belt_material.cre_user
     *
     * @param creUser the value for belt_material.cre_user
     *
     * @mbg.generated
     */
    public void setCreUser(String creUser) {
        this.creUser = creUser == null ? null : creUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column belt_material.cre_date
     *
     * @return the value of belt_material.cre_date
     *
     * @mbg.generated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column belt_material.cre_date
     *
     * @param creDate the value for belt_material.cre_date
     *
     * @mbg.generated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column belt_material.upd_user
     *
     * @return the value of belt_material.upd_user
     *
     * @mbg.generated
     */
    public String getUpdUser() {
        return updUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column belt_material.upd_user
     *
     * @param updUser the value for belt_material.upd_user
     *
     * @mbg.generated
     */
    public void setUpdUser(String updUser) {
        this.updUser = updUser == null ? null : updUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column belt_material.upd_date
     *
     * @return the value of belt_material.upd_date
     *
     * @mbg.generated
     */
    public Date getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column belt_material.upd_date
     *
     * @param updDate the value for belt_material.upd_date
     *
     * @mbg.generated
     */
    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column belt_material.remarks
     *
     * @return the value of belt_material.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column belt_material.remarks
     *
     * @param remarks the value for belt_material.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column belt_material.sort
     *
     * @return the value of belt_material.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column belt_material.sort
     *
     * @param sort the value for belt_material.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}