package com.komehyo.dao.entity;

import java.util.Date;

public class BigType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_type.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_type.good_type
     *
     * @mbg.generated
     */
    private String goodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_type.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_type.cre_user
     *
     * @mbg.generated
     */
    private String creUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_type.cre_date
     *
     * @mbg.generated
     */
    private Date creDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_type.upd_user
     *
     * @mbg.generated
     */
    private String updUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_type.upd_date
     *
     * @mbg.generated
     */
    private Date updDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_type.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_type.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_type.id
     *
     * @return the value of big_type.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_type.id
     *
     * @param id the value for big_type.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_type.good_type
     *
     * @return the value of big_type.good_type
     *
     * @mbg.generated
     */
    public String getGoodType() {
        return goodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_type.good_type
     *
     * @param goodType the value for big_type.good_type
     *
     * @mbg.generated
     */
    public void setGoodType(String goodType) {
        this.goodType = goodType == null ? null : goodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_type.name
     *
     * @return the value of big_type.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_type.name
     *
     * @param name the value for big_type.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_type.cre_user
     *
     * @return the value of big_type.cre_user
     *
     * @mbg.generated
     */
    public String getCreUser() {
        return creUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_type.cre_user
     *
     * @param creUser the value for big_type.cre_user
     *
     * @mbg.generated
     */
    public void setCreUser(String creUser) {
        this.creUser = creUser == null ? null : creUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_type.cre_date
     *
     * @return the value of big_type.cre_date
     *
     * @mbg.generated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_type.cre_date
     *
     * @param creDate the value for big_type.cre_date
     *
     * @mbg.generated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_type.upd_user
     *
     * @return the value of big_type.upd_user
     *
     * @mbg.generated
     */
    public String getUpdUser() {
        return updUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_type.upd_user
     *
     * @param updUser the value for big_type.upd_user
     *
     * @mbg.generated
     */
    public void setUpdUser(String updUser) {
        this.updUser = updUser == null ? null : updUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_type.upd_date
     *
     * @return the value of big_type.upd_date
     *
     * @mbg.generated
     */
    public Date getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_type.upd_date
     *
     * @param updDate the value for big_type.upd_date
     *
     * @mbg.generated
     */
    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_type.remarks
     *
     * @return the value of big_type.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_type.remarks
     *
     * @param remarks the value for big_type.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_type.sort
     *
     * @return the value of big_type.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_type.sort
     *
     * @param sort the value for big_type.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}