package com.komehyo.dao.entity;

import java.util.Date;

public class GemstoneUnit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gemstone_unit.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gemstone_unit.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gemstone_unit.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gemstone_unit.cre_user
     *
     * @mbg.generated
     */
    private String creUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gemstone_unit.cre_date
     *
     * @mbg.generated
     */
    private Date creDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gemstone_unit.upd_user
     *
     * @mbg.generated
     */
    private String updUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gemstone_unit.upd_date
     *
     * @mbg.generated
     */
    private Date updDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gemstone_unit.id
     *
     * @return the value of gemstone_unit.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gemstone_unit.id
     *
     * @param id the value for gemstone_unit.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gemstone_unit.name
     *
     * @return the value of gemstone_unit.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gemstone_unit.name
     *
     * @param name the value for gemstone_unit.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gemstone_unit.remark
     *
     * @return the value of gemstone_unit.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gemstone_unit.remark
     *
     * @param remark the value for gemstone_unit.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gemstone_unit.cre_user
     *
     * @return the value of gemstone_unit.cre_user
     *
     * @mbg.generated
     */
    public String getCreUser() {
        return creUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gemstone_unit.cre_user
     *
     * @param creUser the value for gemstone_unit.cre_user
     *
     * @mbg.generated
     */
    public void setCreUser(String creUser) {
        this.creUser = creUser == null ? null : creUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gemstone_unit.cre_date
     *
     * @return the value of gemstone_unit.cre_date
     *
     * @mbg.generated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gemstone_unit.cre_date
     *
     * @param creDate the value for gemstone_unit.cre_date
     *
     * @mbg.generated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gemstone_unit.upd_user
     *
     * @return the value of gemstone_unit.upd_user
     *
     * @mbg.generated
     */
    public String getUpdUser() {
        return updUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gemstone_unit.upd_user
     *
     * @param updUser the value for gemstone_unit.upd_user
     *
     * @mbg.generated
     */
    public void setUpdUser(String updUser) {
        this.updUser = updUser == null ? null : updUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gemstone_unit.upd_date
     *
     * @return the value of gemstone_unit.upd_date
     *
     * @mbg.generated
     */
    public Date getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gemstone_unit.upd_date
     *
     * @param updDate the value for gemstone_unit.upd_date
     *
     * @mbg.generated
     */
    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }
}