package com.komehyo.dao.entity;

public class GoodExcelWithBLOBs extends GoodExcel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_excel.repair_text
     *
     * @mbg.generated
     */
    private String repairText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_good_excel.request_text
     *
     * @mbg.generated
     */
    private String requestText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_excel.repair_text
     *
     * @return the value of t_good_excel.repair_text
     *
     * @mbg.generated
     */
    public String getRepairText() {
        return repairText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_excel.repair_text
     *
     * @param repairText the value for t_good_excel.repair_text
     *
     * @mbg.generated
     */
    public void setRepairText(String repairText) {
        this.repairText = repairText == null ? null : repairText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_good_excel.request_text
     *
     * @return the value of t_good_excel.request_text
     *
     * @mbg.generated
     */
    public String getRequestText() {
        return requestText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_good_excel.request_text
     *
     * @param requestText the value for t_good_excel.request_text
     *
     * @mbg.generated
     */
    public void setRequestText(String requestText) {
        this.requestText = requestText == null ? null : requestText.trim();
    }
}