package com.komehyo.dao.entity;

public class GoodsWithBLOBs extends Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.repair_text
     *
     * @mbg.generated
     */
    private String repairText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.request_text
     *
     * @mbg.generated
     */
    private String requestText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_return_reason
     *
     * @mbg.generated
     */
    private String goodsReturnReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.repair_text
     *
     * @return the value of t_goods.repair_text
     *
     * @mbg.generated
     */
    public String getRepairText() {
        return repairText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.repair_text
     *
     * @param repairText the value for t_goods.repair_text
     *
     * @mbg.generated
     */
    public void setRepairText(String repairText) {
        this.repairText = repairText == null ? null : repairText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.request_text
     *
     * @return the value of t_goods.request_text
     *
     * @mbg.generated
     */
    public String getRequestText() {
        return requestText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.request_text
     *
     * @param requestText the value for t_goods.request_text
     *
     * @mbg.generated
     */
    public void setRequestText(String requestText) {
        this.requestText = requestText == null ? null : requestText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_return_reason
     *
     * @return the value of t_goods.goods_return_reason
     *
     * @mbg.generated
     */
    public String getGoodsReturnReason() {
        return goodsReturnReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_return_reason
     *
     * @param goodsReturnReason the value for t_goods.goods_return_reason
     *
     * @mbg.generated
     */
    public void setGoodsReturnReason(String goodsReturnReason) {
        this.goodsReturnReason = goodsReturnReason == null ? null : goodsReturnReason.trim();
    }
}