package com.komehyo.dao.entity;

import java.util.Date;

public class International {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_c_international.international_id
     *
     * @mbg.generated
     */
    private String internationalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_c_international.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_c_international.cn
     *
     * @mbg.generated
     */
    private String cn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_c_international.en
     *
     * @mbg.generated
     */
    private String en;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_c_international.jp
     *
     * @mbg.generated
     */
    private String jp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_c_international.other1
     *
     * @mbg.generated
     */
    private String other1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_c_international.other2
     *
     * @mbg.generated
     */
    private String other2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_c_international.module
     *
     * @mbg.generated
     */
    private String module;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_c_international.domain_id
     *
     * @mbg.generated
     */
    private String domainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_c_international.cre_user
     *
     * @mbg.generated
     */
    private String creUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_c_international.cre_date
     *
     * @mbg.generated
     */
    private Date creDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_c_international.upd_user
     *
     * @mbg.generated
     */
    private String updUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_c_international.upd_date
     *
     * @mbg.generated
     */
    private Date updDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_c_international.international_id
     *
     * @return the value of sv_c_international.international_id
     *
     * @mbg.generated
     */
    public String getInternationalId() {
        return internationalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_c_international.international_id
     *
     * @param internationalId the value for sv_c_international.international_id
     *
     * @mbg.generated
     */
    public void setInternationalId(String internationalId) {
        this.internationalId = internationalId == null ? null : internationalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_c_international.type
     *
     * @return the value of sv_c_international.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_c_international.type
     *
     * @param type the value for sv_c_international.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_c_international.cn
     *
     * @return the value of sv_c_international.cn
     *
     * @mbg.generated
     */
    public String getCn() {
        return cn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_c_international.cn
     *
     * @param cn the value for sv_c_international.cn
     *
     * @mbg.generated
     */
    public void setCn(String cn) {
        this.cn = cn == null ? null : cn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_c_international.en
     *
     * @return the value of sv_c_international.en
     *
     * @mbg.generated
     */
    public String getEn() {
        return en;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_c_international.en
     *
     * @param en the value for sv_c_international.en
     *
     * @mbg.generated
     */
    public void setEn(String en) {
        this.en = en == null ? null : en.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_c_international.jp
     *
     * @return the value of sv_c_international.jp
     *
     * @mbg.generated
     */
    public String getJp() {
        return jp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_c_international.jp
     *
     * @param jp the value for sv_c_international.jp
     *
     * @mbg.generated
     */
    public void setJp(String jp) {
        this.jp = jp == null ? null : jp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_c_international.other1
     *
     * @return the value of sv_c_international.other1
     *
     * @mbg.generated
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_c_international.other1
     *
     * @param other1 the value for sv_c_international.other1
     *
     * @mbg.generated
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_c_international.other2
     *
     * @return the value of sv_c_international.other2
     *
     * @mbg.generated
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_c_international.other2
     *
     * @param other2 the value for sv_c_international.other2
     *
     * @mbg.generated
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_c_international.module
     *
     * @return the value of sv_c_international.module
     *
     * @mbg.generated
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_c_international.module
     *
     * @param module the value for sv_c_international.module
     *
     * @mbg.generated
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_c_international.domain_id
     *
     * @return the value of sv_c_international.domain_id
     *
     * @mbg.generated
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_c_international.domain_id
     *
     * @param domainId the value for sv_c_international.domain_id
     *
     * @mbg.generated
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId == null ? null : domainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_c_international.cre_user
     *
     * @return the value of sv_c_international.cre_user
     *
     * @mbg.generated
     */
    public String getCreUser() {
        return creUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_c_international.cre_user
     *
     * @param creUser the value for sv_c_international.cre_user
     *
     * @mbg.generated
     */
    public void setCreUser(String creUser) {
        this.creUser = creUser == null ? null : creUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_c_international.cre_date
     *
     * @return the value of sv_c_international.cre_date
     *
     * @mbg.generated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_c_international.cre_date
     *
     * @param creDate the value for sv_c_international.cre_date
     *
     * @mbg.generated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_c_international.upd_user
     *
     * @return the value of sv_c_international.upd_user
     *
     * @mbg.generated
     */
    public String getUpdUser() {
        return updUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_c_international.upd_user
     *
     * @param updUser the value for sv_c_international.upd_user
     *
     * @mbg.generated
     */
    public void setUpdUser(String updUser) {
        this.updUser = updUser == null ? null : updUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_c_international.upd_date
     *
     * @return the value of sv_c_international.upd_date
     *
     * @mbg.generated
     */
    public Date getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_c_international.upd_date
     *
     * @param updDate the value for sv_c_international.upd_date
     *
     * @mbg.generated
     */
    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }
}