package com.komehyo.dao.entity;

import java.util.Date;

public class Material {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.material
     *
     * @mbg.generated
     */
    private String material;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.cre_user
     *
     * @mbg.generated
     */
    private String creUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.cre_date
     *
     * @mbg.generated
     */
    private Date creDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.upd_user
     *
     * @mbg.generated
     */
    private String updUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.upd_date
     *
     * @mbg.generated
     */
    private Date updDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.id
     *
     * @return the value of material.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.id
     *
     * @param id the value for material.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.material
     *
     * @return the value of material.material
     *
     * @mbg.generated
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.material
     *
     * @param material the value for material.material
     *
     * @mbg.generated
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.cre_user
     *
     * @return the value of material.cre_user
     *
     * @mbg.generated
     */
    public String getCreUser() {
        return creUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.cre_user
     *
     * @param creUser the value for material.cre_user
     *
     * @mbg.generated
     */
    public void setCreUser(String creUser) {
        this.creUser = creUser == null ? null : creUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.cre_date
     *
     * @return the value of material.cre_date
     *
     * @mbg.generated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.cre_date
     *
     * @param creDate the value for material.cre_date
     *
     * @mbg.generated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.upd_user
     *
     * @return the value of material.upd_user
     *
     * @mbg.generated
     */
    public String getUpdUser() {
        return updUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.upd_user
     *
     * @param updUser the value for material.upd_user
     *
     * @mbg.generated
     */
    public void setUpdUser(String updUser) {
        this.updUser = updUser == null ? null : updUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.upd_date
     *
     * @return the value of material.upd_date
     *
     * @mbg.generated
     */
    public Date getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.upd_date
     *
     * @param updDate the value for material.upd_date
     *
     * @mbg.generated
     */
    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.remarks
     *
     * @return the value of material.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.remarks
     *
     * @param remarks the value for material.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.sort
     *
     * @return the value of material.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.sort
     *
     * @param sort the value for material.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}