package com.komehyo.dao.entity;

import java.util.Date;

public class WatchAccessories {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch_accessories.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch_accessories.watch_accessories
     *
     * @mbg.generated
     */
    private String watchAccessories;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch_accessories.cre_user
     *
     * @mbg.generated
     */
    private String creUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch_accessories.cre_date
     *
     * @mbg.generated
     */
    private Date creDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch_accessories.upd_user
     *
     * @mbg.generated
     */
    private String updUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch_accessories.upd_date
     *
     * @mbg.generated
     */
    private Date updDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch_accessories.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch_accessories.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch_accessories.id
     *
     * @return the value of watch_accessories.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch_accessories.id
     *
     * @param id the value for watch_accessories.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch_accessories.watch_accessories
     *
     * @return the value of watch_accessories.watch_accessories
     *
     * @mbg.generated
     */
    public String getWatchAccessories() {
        return watchAccessories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch_accessories.watch_accessories
     *
     * @param watchAccessories the value for watch_accessories.watch_accessories
     *
     * @mbg.generated
     */
    public void setWatchAccessories(String watchAccessories) {
        this.watchAccessories = watchAccessories == null ? null : watchAccessories.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch_accessories.cre_user
     *
     * @return the value of watch_accessories.cre_user
     *
     * @mbg.generated
     */
    public String getCreUser() {
        return creUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch_accessories.cre_user
     *
     * @param creUser the value for watch_accessories.cre_user
     *
     * @mbg.generated
     */
    public void setCreUser(String creUser) {
        this.creUser = creUser == null ? null : creUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch_accessories.cre_date
     *
     * @return the value of watch_accessories.cre_date
     *
     * @mbg.generated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch_accessories.cre_date
     *
     * @param creDate the value for watch_accessories.cre_date
     *
     * @mbg.generated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch_accessories.upd_user
     *
     * @return the value of watch_accessories.upd_user
     *
     * @mbg.generated
     */
    public String getUpdUser() {
        return updUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch_accessories.upd_user
     *
     * @param updUser the value for watch_accessories.upd_user
     *
     * @mbg.generated
     */
    public void setUpdUser(String updUser) {
        this.updUser = updUser == null ? null : updUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch_accessories.upd_date
     *
     * @return the value of watch_accessories.upd_date
     *
     * @mbg.generated
     */
    public Date getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch_accessories.upd_date
     *
     * @param updDate the value for watch_accessories.upd_date
     *
     * @mbg.generated
     */
    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch_accessories.remarks
     *
     * @return the value of watch_accessories.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch_accessories.remarks
     *
     * @param remarks the value for watch_accessories.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch_accessories.sort
     *
     * @return the value of watch_accessories.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch_accessories.sort
     *
     * @param sort the value for watch_accessories.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}