package com.komehyo.dao.entity;

import java.util.Date;

public class Waterproof {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waterproof.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waterproof.waterproof
     *
     * @mbg.generated
     */
    private String waterproof;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waterproof.cre_user
     *
     * @mbg.generated
     */
    private String creUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waterproof.cre_date
     *
     * @mbg.generated
     */
    private Date creDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waterproof.upd_user
     *
     * @mbg.generated
     */
    private String updUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waterproof.upd_date
     *
     * @mbg.generated
     */
    private Date updDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waterproof.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waterproof.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waterproof.id
     *
     * @return the value of waterproof.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waterproof.id
     *
     * @param id the value for waterproof.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waterproof.waterproof
     *
     * @return the value of waterproof.waterproof
     *
     * @mbg.generated
     */
    public String getWaterproof() {
        return waterproof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waterproof.waterproof
     *
     * @param waterproof the value for waterproof.waterproof
     *
     * @mbg.generated
     */
    public void setWaterproof(String waterproof) {
        this.waterproof = waterproof == null ? null : waterproof.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waterproof.cre_user
     *
     * @return the value of waterproof.cre_user
     *
     * @mbg.generated
     */
    public String getCreUser() {
        return creUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waterproof.cre_user
     *
     * @param creUser the value for waterproof.cre_user
     *
     * @mbg.generated
     */
    public void setCreUser(String creUser) {
        this.creUser = creUser == null ? null : creUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waterproof.cre_date
     *
     * @return the value of waterproof.cre_date
     *
     * @mbg.generated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waterproof.cre_date
     *
     * @param creDate the value for waterproof.cre_date
     *
     * @mbg.generated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waterproof.upd_user
     *
     * @return the value of waterproof.upd_user
     *
     * @mbg.generated
     */
    public String getUpdUser() {
        return updUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waterproof.upd_user
     *
     * @param updUser the value for waterproof.upd_user
     *
     * @mbg.generated
     */
    public void setUpdUser(String updUser) {
        this.updUser = updUser == null ? null : updUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waterproof.upd_date
     *
     * @return the value of waterproof.upd_date
     *
     * @mbg.generated
     */
    public Date getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waterproof.upd_date
     *
     * @param updDate the value for waterproof.upd_date
     *
     * @mbg.generated
     */
    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waterproof.remarks
     *
     * @return the value of waterproof.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waterproof.remarks
     *
     * @param remarks the value for waterproof.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waterproof.sort
     *
     * @return the value of waterproof.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waterproof.sort
     *
     * @param sort the value for waterproof.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}