package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.BagsAccessories;

public interface BagsAccessoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bags_accessories
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bags_accessories
     *
     * @mbg.generated
     */
    int insert(BagsAccessories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bags_accessories
     *
     * @mbg.generated
     */
    int insertSelective(BagsAccessories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bags_accessories
     *
     * @mbg.generated
     */
    BagsAccessories selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bags_accessories
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BagsAccessories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bags_accessories
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BagsAccessories record);
}