package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.BeltMaterial;

public interface BeltMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belt_material
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belt_material
     *
     * @mbg.generated
     */
    int insert(BeltMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belt_material
     *
     * @mbg.generated
     */
    int insertSelective(BeltMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belt_material
     *
     * @mbg.generated
     */
    BeltMaterial selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belt_material
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BeltMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belt_material
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BeltMaterial record);
}