package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.BigType;

public interface BigTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_type
     *
     * @mbg.generated
     */
    int insert(BigType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_type
     *
     * @mbg.generated
     */
    int insertSelective(BigType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_type
     *
     * @mbg.generated
     */
    BigType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BigType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BigType record);
}