package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.CaseMaterial;

public interface CaseMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_material
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_material
     *
     * @mbg.generated
     */
    int insert(CaseMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_material
     *
     * @mbg.generated
     */
    int insertSelective(CaseMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_material
     *
     * @mbg.generated
     */
    CaseMaterial selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_material
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CaseMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_material
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CaseMaterial record);
}