package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.GemAccessories;

public interface GemAccessoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_accessories
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_accessories
     *
     * @mbg.generated
     */
    int insert(GemAccessories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_accessories
     *
     * @mbg.generated
     */
    int insertSelective(GemAccessories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_accessories
     *
     * @mbg.generated
     */
    GemAccessories selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_accessories
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GemAccessories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_accessories
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GemAccessories record);
}