package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.GemstoneUnit;

public interface GemstoneUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gemstone_unit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gemstone_unit
     *
     * @mbg.generated
     */
    int insert(GemstoneUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gemstone_unit
     *
     * @mbg.generated
     */
    int insertSelective(GemstoneUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gemstone_unit
     *
     * @mbg.generated
     */
    GemstoneUnit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gemstone_unit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GemstoneUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gemstone_unit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GemstoneUnit record);
}