package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.Gemstone;

public interface GemstoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gemstone
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gemstone
     *
     * @mbg.generated
     */
    int insert(Gemstone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gemstone
     *
     * @mbg.generated
     */
    int insertSelective(Gemstone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gemstone
     *
     * @mbg.generated
     */
    Gemstone selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gemstone
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Gemstone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gemstone
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Gemstone record);
}