package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.GoodBrand;

public interface GoodBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_brand
     *
     * @mbg.generated
     */
    int insert(GoodBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_brand
     *
     * @mbg.generated
     */
    int insertSelective(GoodBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_brand
     *
     * @mbg.generated
     */
    GoodBrand selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodBrand record);
}