package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.GoodExcel;
import com.komehyo.dao.entity.GoodExcelWithBLOBs;

import java.util.List;

public interface GoodExcelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good_excel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good_excel
     *
     * @mbg.generated
     */
    int insert(GoodExcelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good_excel
     *
     * @mbg.generated
     */
    int insertSelective(GoodExcelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good_excel
     *
     * @mbg.generated
     */
    GoodExcelWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good_excel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodExcelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good_excel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GoodExcelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good_excel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodExcel record);

    List<GoodExcelWithBLOBs> selectYesterday();
}