package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.JewelrySize;

public interface JewelrySizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewelry_size
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewelry_size
     *
     * @mbg.generated
     */
    int insert(JewelrySize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewelry_size
     *
     * @mbg.generated
     */
    int insertSelective(JewelrySize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewelry_size
     *
     * @mbg.generated
     */
    JewelrySize selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewelry_size
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JewelrySize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewelry_size
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JewelrySize record);
}