package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.JewelrySize2;

public interface JewelrySize2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewelry_size2
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewelry_size2
     *
     * @mbg.generated
     */
    int insert(JewelrySize2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewelry_size2
     *
     * @mbg.generated
     */
    int insertSelective(JewelrySize2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewelry_size2
     *
     * @mbg.generated
     */
    JewelrySize2 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewelry_size2
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JewelrySize2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jewelry_size2
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JewelrySize2 record);
}