package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.Material1;

public interface Material1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material1
     *
     * @mbg.generated
     */
    int insert(Material1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material1
     *
     * @mbg.generated
     */
    int insertSelective(Material1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material1
     *
     * @mbg.generated
     */
    Material1 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material1
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Material1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Material1 record);
}