package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.SaleRank;

public interface SaleRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_rank
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_rank
     *
     * @mbg.generated
     */
    int insert(SaleRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_rank
     *
     * @mbg.generated
     */
    int insertSelective(SaleRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_rank
     *
     * @mbg.generated
     */
    SaleRank selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_rank
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SaleRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_rank
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SaleRank record);
}