package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.SmallgoodsBagsAccessories;

public interface SmallgoodsBagsAccessoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_bags_accessories
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_bags_accessories
     *
     * @mbg.generated
     */
    int insert(SmallgoodsBagsAccessories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_bags_accessories
     *
     * @mbg.generated
     */
    int insertSelective(SmallgoodsBagsAccessories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_bags_accessories
     *
     * @mbg.generated
     */
    SmallgoodsBagsAccessories selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_bags_accessories
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmallgoodsBagsAccessories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_bags_accessories
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmallgoodsBagsAccessories record);
}