package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.SmallgoodsMaterial1;

public interface SmallgoodsMaterial1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_material1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_material1
     *
     * @mbg.generated
     */
    int insert(SmallgoodsMaterial1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_material1
     *
     * @mbg.generated
     */
    int insertSelective(SmallgoodsMaterial1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_material1
     *
     * @mbg.generated
     */
    SmallgoodsMaterial1 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_material1
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmallgoodsMaterial1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_material1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmallgoodsMaterial1 record);
}