package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.SmallgoodsSize;

public interface SmallgoodsSizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_size
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_size
     *
     * @mbg.generated
     */
    int insert(SmallgoodsSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_size
     *
     * @mbg.generated
     */
    int insertSelective(SmallgoodsSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_size
     *
     * @mbg.generated
     */
    SmallgoodsSize selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_size
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmallgoodsSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallgoods_size
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmallgoodsSize record);
}