package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.WatchSize;

public interface WatchSizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch_size
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch_size
     *
     * @mbg.generated
     */
    int insert(WatchSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch_size
     *
     * @mbg.generated
     */
    int insertSelective(WatchSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch_size
     *
     * @mbg.generated
     */
    WatchSize selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch_size
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WatchSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch_size
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WatchSize record);
}