package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.WatchAccessories;

public interface WatchAccessoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch_accessories
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch_accessories
     *
     * @mbg.generated
     */
    int insert(WatchAccessories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch_accessories
     *
     * @mbg.generated
     */
    int insertSelective(WatchAccessories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch_accessories
     *
     * @mbg.generated
     */
    WatchAccessories selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch_accessories
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WatchAccessories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch_accessories
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WatchAccessories record);
}