package com.komehyo.dao.mapper.app;

import com.komehyo.dao.entity.Waterproof;

public interface WaterproofMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waterproof
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waterproof
     *
     * @mbg.generated
     */
    int insert(Waterproof record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waterproof
     *
     * @mbg.generated
     */
    int insertSelective(Waterproof record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waterproof
     *
     * @mbg.generated
     */
    Waterproof selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waterproof
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Waterproof record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waterproof
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Waterproof record);
}